{% set cov = "coverage run --source=importnb --omit=\"*json_parser*\" --branch --append -m" %}
{% set version = "2023.11.1" %}
{% set cov_threshold = 63 %}
{% set cov = "coverage run --source=importnb --omit=\"*json_parser*\" --branch --append -m" %}

package:
  name: importnb
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/importnb/importnb-{{ version }}.tar.gz
  sha256: 95a745ac7299a81f776e8210e8ad77f05731dfce7bad79eb85e08ed37a2488c0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python
  entry_points:
    - importnb = importnb.__main__:main

requirements:
  host:
    - hatch-vcs
    - hatchling
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  files:
    - test_importnb.ipynb
  requires:
    - coverage
    - pip
    - pytest
  imports:
    - importnb
  commands:
    - pip check
    - {{ cov }} importnb --help
    - {{ cov }} importnb -m test_importnb
    - {{ cov }} pytest -vv --doctest-modules
    - coverage report --show-missing --skip-covered --fail-under={{ cov_threshold }}

about:
  home: https://github.com/deathbeds/importnb
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: import jupyter notebooks as python modules and scripts.
  doc_url: https://importnb.readthedocs.io
  doc_source_url: https://github.com/deathbeds/importnb/tree/{{ version }}/docs
  description: |
    importnb imports notebooks as python modules.

extra:
  recipe-maintainers:
    - ocefpaf
    - bollwyvl
