{% set version = "0.5.5" %}

package:
  name: importnb
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/importnb/importnb-{{ version }}.tar.gz
  sha256: 96e93f51dec170e739b79d588fe48d26f6dd3f2f787562a45ba55e2e541cac59

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3
    - pip
    - pytest-runner
    - wheel >=0.31.0
    - twine >=1.11.0
  run:
    - python >=3
    - setuptools
    - dataclasses
    - nbconvert
    # importlib_resources will be [not py>36] and this will be arch again :-(
    - importlib_resources

test:
  imports:
    - importnb

about:
  home: https://github.com/deathbeds/importnb
  license: BSD 3-Clause
  license_file: LICENSE
  summary: Import .ipynb files as modules in the system path

extra:
  recipe-maintainers:
    - ocefpaf
