{% set version = "0.8.0" %}

package:
  name: importnb
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/importnb/importnb-{{ version }}.tar.gz
  sha256: 96a0fe94d23ca2c4acc51455836ff1b2bad8ac4bf51ce67d9e75294d59054cc0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python
  entry_points:
    - importnb = importnb.__main__:main

requirements:
  host:
    - hatch-vcs
    - hatchling
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  requires:
    - pip
  imports:
    - importnb
  commands:
    - pip check
    - importnb --help
    - python -c "v = __import__('importnb._version')._version.__version__; print(v); assert v == '{{ version }}'"

about:
  home: https://github.com/deathbeds/importnb
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: import jupyter notebooks as python modules and scripts.
  doc_url: https://importnb.readthedocs.io
  doc_source_url: https://github.com/deathbeds/importnb/tree/{{ version }}/docs
  description: |
    importnb imports notebooks as python modules.

extra:
  recipe-maintainers:
    - ocefpaf
    - bollwyvl
