{% set version = "2023.11.1" %}
{% set min_python = "python >=3.8" %}

package:
  name: importnb
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/i/importnb/importnb-{{ version }}.tar.gz
  sha256: 95a745ac7299a81f776e8210e8ad77f05731dfce7bad79eb85e08ed37a2488c0

build:
  number: 1
  noarch: python

requirements:
  host:
    - {{ min_python }}
  run:
    - {{ min_python }}

outputs:
  - name: importnb
    build:
      noarch: python
      script:
        - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
      entry_points:
        - importnb = importnb.__main__:main
    requirements:
      host:
        - {{ min_python }}
        - hatch-vcs
        - hatchling
        - pip
      run:
        - {{ min_python }}
        - importlib-metadata >=4.8.3
    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - importnb
      commands:
        - pip check

  - name: importnb-with-toml
    build:
      noarch: python
    requirements:
      host:
        - {{ min_python }}
      run:
        - {{ min_python }}
        - {{ pin_subpackage("importnb", exact=True) }}
        - tomli
    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - importnb
      commands:
        - pip check

  - name: importnb-with-yaml
    build:
      noarch: python
    requirements:
      host:
        - {{ min_python }}
      run:
        - {{ min_python }}
        - {{ pin_subpackage("importnb", exact=True) }}
        - ruamel.yaml
    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - importnb
      commands:
        - pip check

  - name: importnb-with-ipython
    build:
      noarch: python
    requirements:
      host:
        - {{ min_python }}
      run:
        - {{ min_python }}
        - {{ pin_subpackage("importnb", exact=True) }}
        - ipython
    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - importnb
      commands:
        - pip check

  - name: importnb-with-doit
    build:
      noarch: python
    requirements:
      host:
        - {{ min_python }}
      run:
        - {{ min_python }}
        - {{ pin_subpackage("importnb", exact=True) }}
        - doit
    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - importnb
      commands:
        - pip check

  - name: importnb-with-all
    build:
      noarch: python
    requirements:
      host:
        - {{ min_python }}
      run:
        - {{ min_python }}
        - {{ pin_subpackage("importnb-with-doit", exact=True) }}
        - {{ pin_subpackage("importnb-with-ipython", exact=True) }}
        - {{ pin_subpackage("importnb-with-toml", exact=True) }}
        - {{ pin_subpackage("importnb-with-yaml", exact=True) }}
        - {{ pin_subpackage("importnb", exact=True) }}
    test:
      # files:
      #   - test_importnb.ipynb
      source_files:
        - conftest.py
        - docs
      requires:
        - coverage
        - pip
        - pytest
        - tomli-w
        - python {{ python_min }}
      imports:
        - importnb
      commands:
        {% set cov = 'coverage run --source=importnb --omit="*json_parser*" --branch --append -m' %}
        {% set pytest = '-vv --color=yes --tb=long --doctest-modules' %}
        - pip check
        - {{ cov }} importnb --help
        - {{ cov }} pytest {{ pytest }}
        - {{ cov }} IPython -m pytest -- {{ pytest }}
        - coverage report --show-missing --skip-covered --fail-under=75

about:
  home: https://github.com/deathbeds/importnb
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: import jupyter notebooks as python modules and scripts.
  doc_url: https://importnb.readthedocs.io
  doc_source_url: https://github.com/deathbeds/importnb/tree/{{ version }}/docs

extra:
  feedstock-name: importnb
  recipe-maintainers:
    - ocefpaf
    - bollwyvl
